trigger:
  branches:
    include:
      - master
      - develop
      - hotfix/*
    exclude:
      - release/*

pr:
  branches:
    include:
      - master
      - develop

variables:
  tag: $(Build.BuildId)-$(Build.SourceVersion)
  containerRegistryServiceConnection: 'Docker.Registry.Service.Connection.To.ECR'
  wizcliUrl: 'https://wizcli.app.wiz.io/latest/wizcli-linux-amd64'
  resultRepository: result
  voteRepository: vote
  workerRepository: worker

stages:
  - stage: Build
    displayName: Build Stage
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: Build
        displayName: Build and Push Docker Images
        steps:
          - checkout: self
            clean: true
            fetchTags: true

          - task: Docker@2
            displayName: Build and Push Result Image
            inputs:
              containerRegistry: $(containerRegistryServiceConnection)
              repository: $(resultRepository)
              command: 'buildAndPush'
              Dockerfile: './result/Dockerfile'
              buildContext: './result'
              tags: '$(tag)'

          - task: Docker@2
            displayName: Build and Push Vote Image
            inputs:
              containerRegistry: $(containerRegistryServiceConnection)
              repository: $(voteRepository)
              command: 'buildAndPush'
              Dockerfile: './vote/Dockerfile'
              buildContext: './vote'
              tags: '$(tag)'

          - task: Docker@2
            displayName: Build and Push Worker Image
            inputs:
              containerRegistry: $(containerRegistryServiceConnection)
              repository: $(workerRepository)
              command: 'buildAndPush'
              Dockerfile: './worker/Dockerfile'
              buildContext: './worker'
              tags: '$(tag)'

          - task: CmdLine@2
            displayName: Download and Authenticate WizCLI
            inputs:
              script: |
                echo "Downloading WizCLI..."
                sudo curl -o /usr/bin/wizcli $(wizcliUrl)
                sudo chmod +x /usr/bin/wizcli
                /usr/bin/wizcli auth --id $(WIZ_CLIENT_ID) --secret $(WIZ_CLIENT_SECRET)

          - task: CmdLine@2
            displayName: Scan Docker Images with WizCLI
            inputs:
              script: |
                /usr/bin/wizcli docker scan --image '$(containerRegistryServiceConnection)/$(resultRepository):$(tag)';
                /usr/bin/wizcli docker scan --image '$(containerRegistryServiceConnection)/$(voteRepository):$(tag)';
                /usr/bin/wizcli docker scan --image '$(containerRegistryServiceConnection)/$(workerRepository):$(tag)';
                if [[ $? -ne 0 ]]; then
                  echo "##vso[task.logissue type=error] Wiz Scan failed"
                  exit 1;
                fi

