---
{{- if .Values.result.enabled  }}
# result
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "result.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "result.fullname" . }}
  {{- include "result.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.result.replicas }}
  selector:
    matchLabels:
      app: {{ include "result.fullname" . }}
    {{- include "result.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "result.fullname" . }}
      {{- include "result.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.result.kubernetesClusterDomain }}
        image: {{ .Values.image.repository }}/{{ .Values.result.result.image.name }}:{{ .Values.result.result.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.result.result.imagePullPolicy }}
        name: result
        ports:
        - containerPort: {{ .Values.result.result.containerPort }}
        resources: {{- toYaml .Values.result.result.resources | nindent 10 }}
        {{-  if .Values.result.result.probe.enableLivenessProbe }}
        livenessProbe: {{- toYaml .Values.result.result.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.result.result.probe.enableReadinessProbe }}
        readinessProbe: {{- toYaml .Values.result.result.readinessProbe | nindent 10 }}
        {{- end }}
      initContainers:
      - command:
        - sh
        - -c
        - until nc -vz {{ include "db.fullname" . }} 5432; do echo
          waiting for db; sleep 2; done
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.result.kubernetesClusterDomain }}
        image: {{ .Values.image.repository }}/{{ .Values.result.waitForDb.image.name }}:{{ .Values.result.waitForDb.image.tag | default .Chart.AppVersion }}
        name: wait-for-db
        imagePullPolicy: IfNotPresent
        resources: {}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
{{- end }}
---
{{- if .Values.vote.enabled  }}
# vote
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vote.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "vote.fullname" . }}
  {{- include "vote.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.vote.replicas }}
  selector:
    matchLabels:
      app: {{ include "vote.fullname" . }}
    {{- include "vote.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "vote.fullname" . }}
      {{- include "vote.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.vote.kubernetesClusterDomain }}
        image: {{ .Values.image.repository }}/{{ .Values.vote.vote.image.name }}:{{ .Values.vote.vote.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.vote.vote.imagePullPolicy }}
        name: vote
        ports:
        - containerPort: {{ .Values.vote.vote.containerPort }}
        resources: {{- toYaml .Values.vote.vote.resources | nindent 10 }}
        {{-  if .Values.vote.vote.probe.enableLivenessProbe }}
        livenessProbe: {{- toYaml .Values.vote.vote.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.vote.vote.probe.enableReadinessProbe }}
        readinessProbe: {{- toYaml .Values.vote.vote.readinessProbe | nindent 10 }}
        {{- end }}
      initContainers:
      - command:
        - sh
        - -c
        - until nc -vz {{ include "redis.fullname" . }} 6379; do echo
          waiting for db; sleep 2; done
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.vote.kubernetesClusterDomain }}
        image: {{ .Values.image.repository }}/{{ .Values.vote.waitForRedis.image.name }}:{{ .Values.vote.waitForRedis.image.tag | default .Chart.AppVersion }}
        name: wait-for-redis
        imagePullPolicy: IfNotPresent
        resources: {}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
{{- end }}
---
{{- if .Values.worker.enabled  }}
# worker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "worker.fullname" . }}
  {{- include "worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ include "worker.fullname" . }}
    {{- include "worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "worker.fullname" . }}
      {{- include "worker.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.worker.kubernetesClusterDomain }}
        image: {{ .Values.image.repository }}/{{ .Values.worker.worker.image.name }}:{{ .Values.worker.worker.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.worker.worker.imagePullPolicy }}
        name: worker
        ports:
        - containerPort: {{ .Values.worker.worker.containerPort }}
        resources: {{- toYaml .Values.worker.worker.resources | nindent 10 }}
      initContainers:
      - command:
        - sh
        - -c
        - until nc -vz {{ include "db.fullname" . }} 5432; do echo
          waiting for db; sleep 2; done
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.worker.kubernetesClusterDomain }}
        image: {{ .Values.image.repository }}/{{ .Values.worker.waitForDb.image.name }}:{{ .Values.worker.waitForDb.image.tag | default .Chart.AppVersion }}
        name: wait-for-db
        imagePullPolicy: IfNotPresent
        resources: {}
      - command:
        - sh
        - -c
        - until nc -vz {{ include "redis.fullname" . }} 6379; do echo
          waiting for db; sleep 2; done
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.worker.kubernetesClusterDomain }}
        image: {{ .Values.image.repository }}/{{ .Values.worker.waitForRedis.image.name }}:{{ .Values.worker.waitForRedis.image.tag | default .Chart.AppVersion }}
        name: wait-for-redis
        imagePullPolicy: IfNotPresent
        resources: {}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
{{- end }}
---