---
{{- if .Values.db.enabled  }}
# db
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "db.labels" . | nindent 4 }}
data:
  POSTGRES_PASSWORD: {{ required "db.secret.postgresPassword is required" .Values.db.secret.postgresPassword | b64enc | quote }}
type: Opaque
{{- end }}
---